[package]
name = "r3_core"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.8", features = ["rwh_05"] }
env_logger = "0.11.6"
log = "0.4.25"
wgpu = "24.0.1"
tokio = {version = "1.43.0", features = ["full"]}
bytemuck = { version = "1.16", features = [ "derive" ] }
image = "0.25.5"
slotmap = "1.0.7"
reflect = "0.0.14"