[package]
name = "r3_core"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.9", features = ["rwh_05"] }
env_logger = "0.11.6"
wgpu = "24.0.1"
tokio = {version = "1.44.0", features = ["full"]}
bytemuck = { version = "1.22", features = [ "derive" ] }
image = "0.25.5"
cgmath = "0.18.0"

strong_count = { path = "../strong_count" }